### ISSUE TITLE
Fallout 76 Support

### ISSUE THREAD

**Issue by srhinos** [jonwd7/nifskope#31]
Fallout 76 will more than likely never receive official mod support. Its needed to just accept that fact and just rip the band-aid off. 

On that note, it feels very crappy to hold this project hostage until they make hard yes/no decision. The task of updating the tooling of this project to support 76 modding is far beyond non-trival. It would be weeks of work to just gain a deep enough understanding of all the moving parts of this project and where to even begin modifying the source code to enable this. 

I spent about 6 hours last night dicking around with the source in an attempt to be able to successfully read a nif file and then write it without modifications and never succeeded. Is it a problem with the nif standard XML (that is also maintained by this project's developers)? is there an issue within the code for nifskope? no idea. 

The decision to block this project is not noble either if the intent was to block cheaters. There is already rampant cheating in the game as a few developers have taken this and over the coarse of a few months, done the work I described and are now selling their closed source tooling to people to cheat. At this point, the only person the halt is affecting is the weekend modder like myself who enjoys fucking around with games I play when not working. 

Would love to see the block stopped so the 76 mod community can move past basic texture swaps and UI SWF mods.

**Comment by Underp4ntz** [comment]
They talked about Mod support in a recent interview... They will still do it, but i guess they need to implement their new monetization system and after that fix some stuff that probably will affect modding too.

I'am almost 100% sure modding will be monetized since you need private servers. You probably need Fallout 1st which gives you a Mod Server with verification tools so the mods and versions match with the players. (Unreal Tournament) did that pretty well even if you did not have the mod they auto updated it for you from the server.

I do not believe Bethesda will release Server Tools so we can host our own servers. That would be great if we get it but forget that...


And Didnt NifSkope told some people they have a version that works with importing models but since the mod support is not here yet they wont release it... which i find a bit odd... Cosplayers love to extract the models for making props and stuff..

So I hope NifSkope will release the version that supports Fallout 76 Models so Cosplayers and others can use it.

**Comment by eckserah** [comment]
You guys do know that the dev8 version can open fallout 76 nifs right?

**Comment by jonwd7** [comment]
> You guys do know that the dev8 version can open fallout 76 nifs right?

They might not but it wouldn't really change the "point" of the tirade in the OP.  I intentionally block editing.  It's trivial to reverse though... you just implement the read skipping for shader blocks for the writes.

Lastly, there's already a branch (actually, it was independent from my work) out there that supports editing.  If OP was as passionate about modding FO76 as he professes, he would have ended up in the Discord servers where this build exists.

**Comment by srhinos** [comment]
> you just implement the read skipping for shader blocks for the writes.
That is non-trival for someone who does not know your code base, has never worked in your code base, and the code base is over a decade old with commits from several people. That is not a trivial task for any random person to do.

>  he would have ended up in the Discord servers where this build exists.
I'm the one who built it on the Fallout Datamining Discord. I attempted to edit this to get it to work but could not find relevant code beyond removing the single line blocking the save function from working. If there are others, why respond in the way you did and not link directly to them? What do you gain by not just dropping a link when I am even 1% interested in a project you've put any amount of time and effort into?

>You guys do know that the dev8 version can open fallout 76 nifs right?
dev8 has **always** been able to open nifs. you were not able to save them as they became corrupted after the save. We had a lengthy conversation about this in your discord several months ago and said something to the affect "yeah thats pretty garbage" when I was complaining about this.

again, why go thru such an effort to reply to me in this way now instead of months ago? None of us are children, no reason to act that way.

**Comment by srhinos** [comment]
As a follow up, in this discord server:
https://discord.gg/qxQ7tSY

I went ahead and custom built it and then talked about my issues with basic processes ie open -> save -> close -> reopen

https://discordapp.com/channels/602253035061903368/699708015502426193/711646685993893980

I would be ECSTATIC to get corrected on what I was doing wrong as I can very easily rebuild it with these suggested changes

**Comment by ousnius** [comment]
@srhinos There are people who don't want to be the ones making it possible to edit files of a multiplayer game that doesn't officially support modding at this point. Otherwise, NifSkope would just allow the save and have the code.

**Comment by macwilk** [comment]
> @srhinos There are people who don't want to be the ones making it possible to edit files of a multiplayer game that doesn't officially support modding at this point. Otherwise, NifSkope would just allow the save and have the code. Any additional words or thoughts put in by jonwd7 are a bonus - you want it you do it.

This argument is moot as they’ll never officially support mods of any kind in any reasonable time frame. The mod community exists for this game regardless as I noted in the post above. Tools like this already exist but use stolen code and are locked behind hefty pay gates on hacking forums. 

This altruism being displayed is only harming the hobbyist modder who wants to make small tweaks to nif files. I was interested in porting 76 assets to fallout 4 as well but cannot make the basic modifications to their nif files but cannot do this. 

Just because your frame of thought immediately gravitates to cheating, doesn’t mean that that’s what this tool will be used for.

**Comment by jonwd7** [comment]
> None of us are children, no reason to act that way.

Pointing out that you went on a tirade calling into question my morals does not make me a child.  Reacting so negatively to my pointing it out kinda does.  To quote:  `The decision to block this project is not noble...`  You sounded petulant in your OP, so I adjusted my tone accordingly.  If we were all adults here, the OP probably wouldn't have called me or other aspects of the project **crappy**, **ignoble**, or a **hostage-taker**.  The last one is a real doozy as you are implying I've taken _my own copyrighted work_ violently, by force, and I want something in exchange for it.  The work that is freely viewable in my commit log.  Restated: my work is actually not mine, I am obligated to share it, and if I don't, I'm committing some moral crime, hindering progress, and bringing down an entire community. 

That was the sum total of your argument, so forgive me for reacting negatively.  Furthermore, I can't be holding anything hostage as what is public is all I have.  I have no interest in saving the files, so I never wrote it. 

If you think my assessment of your tone was incorrect, I'll point out you're now making sure to state that someone (your grammar is ambiguous) said that my decision was "garbage" in Eckserah's server, which there were plenty of other ways to remind him without reiterating how garbage you think my decision making is. 

> why go thru such an effort to reply to me in this way now instead of months ago?

Why is this about you?  I was replying to and quoting Eckserah, not you.  I had no expectation that you would ever see or respond to it.  It was in fact my very hope that you would _not_, as I knew months ago when you posted the ticket that _any_ response from me would be met in this way, hence _not_ responding then, since your entire ticket is an attack on my decision making instead of something more constructive. 

I replied (to Eckserah) to clarify that buried somewhere in the text above him was an actual request to make editing possible, not just opening.

> I'm the one who built it on the Fallout Datamining Discord

Since I don't know you and have never been in that Discord, one might surmise that I was talking about an entirely different fork.

The reason I made Dev 8 public at all was because someone was posting a build in modding servers (like xEdit) that could open and edit many FO76 files, but didn't have entirely complete or correct decoding and had no rendering support for the FO76 asset pipeline.  I had held onto Dev 8 privately from November 2018 until mid-August 2019 when that build was posted.  Once it was posted, I immediately pushed my commits and uploaded a release as the "damage was already done" so to speak, and anyone who really wanted to edit FO76 NIFs could use the other build instead of bothering me.  I did _not_ want their build catching on for general usage as it employed a bunch of nif.xml edits that were nasty for the performance of all Bethesda NIFs' shader properties, and hence, my release.

What I cared about was that I was not the **first** person to publicly post all of the decoding or a working build and it had little to do with cheating.  I wanted someone both interested and capable to figure it out on their own, so that they could be the "FO76 Guys".  Because if I'd posted everything right away in November, I would have been _the_ FO76 Guy and I was not going to deal with indefinitely supporting a game that wasn't intended to be modded.  I also couldn't really trust Bethesda that modding client-side files wasn't going to manage to crash their servers, since so incredibly much of the game is client-side when it shouldn't be.  I'm **allowed the choice to indemnify myself in that regard**, despite your beliefs that I have some moral obligation to you or the Fallout 76 community. 

So, it took almost 10 months, but when there were actual contenders for the "FO76 Guys" I uploaded everything I had and washed my hands of it.  They could rebase off my work and go on supporting FO76 modding.  I'm sorry that apparently nothing ever came of it, but how that invites a tirade against me is unclear.  I did my part, and I passed it onto people in your very community.  

**Maybe, what if when nobody is determined and capable enough to support the mod tooling for a game that is not intended to be modded, this means that maybe the game shouldn't be modded?**  Why does someone capable yet uninterested like me owe you?

> If there are others, why respond in the way you did and not link directly to them? What do you gain by not just dropping a link

I will counter and ask why you didn't just turn around and ask your Fallout brethren what fork I was talking about.  What do you gain by forcing me to explain myself?  It's kind of hard to link to files from someone in a modding discord with a ton of traffic from 10 months ago, especially when I don't remember their name, **I no longer use Discord**, and I'm not even in any servers anymore.

What I _can_ tell you is that it was 2-3 individuals that were prominent in xEdit et al., and I'm 99% certain that at least one of them is in the datamining discord, so how you are unaware of their fork is beyond me.  Maybe none of them cared about editing, only viewing, so they stopped their own fork?  Hell, I think maybe Eckserah was one of them.  He may have been the one relaying the serialization logic for the niobjects to the other guys. 

> That is non-trival for someone who does not know your code base, has never worked in your code base, and the code base is over a decade old with commits from several people. That is not a trivial task for any random person to do.

It's pretty trivial when the read skipping **is in its own commit for anyone to view** and then copy to the writes. The age and size of the codebase and amount of contributors has _no bearing_ on your ability to look at the commits around **November 2018** to see what I did.

> This argument is moot as they’ll never officially support mods of any kind in any reasonable time frame. The mod community exists for this game regardless as I noted in the post above. Tools like this already exist but use stolen code and are locked behind hefty pay gates on hacking forums.

Funny... ousnius didn't mention cheating or hacking anywhere.  Also if you think hacking tools rely on the serialization and deserialization code of meshes, then I would say its _your_ argument that's moot, you know nothing about hacking or cheating, and that you're grasping at some kind of morality straw to try to force people to do your bidding.  You seem to be the only one making it about cheating, as the only argument thus far has been "cheating happens anyway, so why not facilitate it yourself?" 

> This altruism being displayed is only harming the hobbyist modder who wants to make small tweaks to nif files. I was interested in porting 76 assets to fallout 4

It's deeply ironic you talk about altruism when you actually do not care about the greater good of FO76 modding and you just want to take content from FO76 and put it into FO4, something which is expressly forbidden by Bethesda.  And spare me the personal use argument, as it's beside the point:  You want one thing while pretending it's about the other.  Also unless I'm mistaken, you can export FO76 files as OBJ in my release, which allows you to port if you really wanted. 

> locked behind hefty pay gates on hacking forums.

Just FYI, if I ever expressly supported FO76 modding, it would be behind a paygate.  Why? Because I only believe in modding private worlds, and private worlds already cost money.  Paygating modding would then limit modding mostly to people on private worlds, i.e. the people who care enough to be paying for it.  It also compensates me for my lack of interest.  Other than porting CBBE to FO76 during the very first B.E.T.A. (as a joke) I don't have any real interest in modding the game since private servers are too costly for me to justify.  

I care about the validity of the decoding and the closeness of the mesh preview, and that's pretty much all anybody will ever convince me to care about.  Open tickets about either of those and you won't see me lambasting you.

**Comment by srhinos** [comment]
Okay, wew. I'd hardly call what I wrote a **tirade**. I write some quick paragraphs after hours of fucking with badly documented code.

I'm not gonna continue this cycle of quoting small pieces of the post and churning out 500+ character response paragraphs.

Simply put, you are the dev of this project. If you don't want to publicly commit changes for the fo76 stuff, fine. I'm not demanding you put in the work yourself and if you had stated that, I'd totally understand. 

What did frustrate me was reading your responses in the main repo here:
https://github.com/niftools/nifskope/issues/171

The fact that you HAD put in work to upgrade this tool to work with fo76, you HAD a locally working copy, and then you withheld this build because you had a moral obligation to prevent cheating was just.... what?

I then decided "Oh, I'll ask about it because the issue is a year old, I bet they're pretty reasonable, most people are" but the forums are closed, the discord is deleted, all resources to contact anyone beyond an issue is missing.

Then when source diving, I notice you purposely committed code to prevent fallout 76 nifs from functioning yet (as also demonstrated in that issue), you're perfectly fine if your tool can work with other online games like RO2 or Wizard101, theres no code to specifically prevent it from working with nif files from other specific games **besides** fallout 76.

THAT is where my frustration stemmed from and why I decided to open an issue here. To me, it felt like you specifically targeted fallout 76 as a game you wanted to NEVER be supported and made active attempts to prevent it from ever occurring on **your** org's repo. That being said, it is your organization's repo and if you want to block fallout 76, thats totally up to you. If you want to charge $420.69 for the tool, great. I support your right to get paid from work you've done. I never said you don't have that right and would never demand you did work for free. The issue I had was how fucking impossible it was to get in contact with literally anyone who could help me dig thru the code and figure out my problem.

Would love to:

1) get a link to where someone is developing this tool further for fallout 76. I got 3 dms on discord from people who are in the same boat as me and cannot find where this is being actively developed at. the xedit discord server? Would love a link!

if not,

2) Get some eyes on the issue I was having with saving and some help fixing the issue. You don't have to do literally anything beyond helping me navigate your code and working thru the problem. I don't have the time to dedicate to working dozens of hours on a code base I am clueless about to implement a fix that'd probably take you 30 mins as I have never worked with writing creation/gamebryo tools before let alone nifs.

happy to open a new issue if option 2 is in the cards.
